List<Map<String, dynamic>> btn_chartList = [
  {
    'text': 'TopViewer',
    'width': 143.0,
    'height': 40.0,
    'iconpath': 'assets/icons/s1.png',
  },
  {
    'text': 'Badge name',
    'width': 136.0,
    'height': 40.0,
    'iconpath': 'assets/icons/s2.png',
  },
  {
    'text': 'Badge name',
    'width': 136.0,
    'height': 40.0,
    'iconpath': 'assets/icons/s3.png',
  },
  {
    'width': 170.0,
    'height': 40.0,
    'text': 'Long badge name',
    'iconpath': 'assets/icons/s4.png',
  },
  {
    'text': 'TopViewer',
    'width': 143.0,
    'height': 40.0,
    'iconpath': 'assets/icons/s1.png',
  },
  {
    'text': 'Badge name',
    'width': 136.0,
    'height': 40.0,
    'iconpath': 'assets/icons/s2.png',
  },
  {
    'text': 'Badge name',
    'width': 136.0,
    'height': 40.0,
    'iconpath': 'assets/icons/s3.png',
  },
  {
    'width': 170.0,
    'height': 40.0,
    'text': 'Long badge name',
    'iconpath': 'assets/icons/s4.png',
  },
  {
    'text': 'TopViewer',
    'width': 143.0,
    'height': 40.0,
    'iconpath': 'assets/icons/s1.png',
  },
  {
    'text': 'Badge name',
    'width': 136.0,
    'height': 40.0,
    'iconpath': 'assets/icons/s2.png',
  },
  {
    'text': 'Badge name',
    'width': 136.0,
    'height': 40.0,
    'iconpath': 'assets/icons/s3.png',
  },
  {
    'width': 170.0,
    'height': 40.0,
    'text': 'Long badge name',
    'iconpath': 'assets/icons/s4.png',
  },
  {
    'text': 'TopViewer',
    'width': 143.0,
    'height': 40.0,
    'iconpath': 'assets/icons/s1.png',
  },
  {
    'text': 'Badge name',
    'width': 136.0,
    'height': 40.0,
    'iconpath': 'assets/icons/s2.png',
  },
  {
    'text': 'Badge name',
    'width': 136.0,
    'height': 40.0,
    'iconpath': 'assets/icons/s3.png',
  },
  {
    'width': 170.0,
    'height': 40.0,
    'text': 'Long badge name',
    'iconpath': 'assets/icons/s4.png',
  },
  {
    'text': 'TopViewer',
    'width': 143.0,
    'height': 40.0,
    'iconpath': 'assets/icons/s1.png',
  },
  {
    'text': 'Badge name',
    'width': 136.0,
    'height': 40.0,
    'iconpath': 'assets/icons/s2.png',
  },
  {
    'text': 'Badge name',
    'width': 136.0,
    'height': 40.0,
    'iconpath': 'assets/icons/s3.png',
  },
  {
    'width': 170.0,
    'height': 40.0,
    'text': 'Long badge name',
    'iconpath': 'assets/icons/s4.png',
  },
];
